### ISSUE TITLE
Login broken using inrupt.net webid

### ISSUE THREAD

**Issue by timbl** [solid/solidcommunity.net_operations#3]
![](https://files.gitter.im/5f7eeca5d73408ce4ff0f9bd/75mU/image.png)

**Comment by jaxoncreed** [comment]
I'm unable to replicate this issue. It looks like there was a problem when this widnow was launched. Does the problem continue to happen?

**Comment by timbl** [comment]
Yup I can't either.  May have been a transient problem with debris in my browser's LocalStorage and cookies. Closing as unreproduceable.
