### ISSUE TITLE
Error accessing /.meta.acl

### ISSUE THREAD

**Issue by angelo-v** [solid/solidcommunity.net_operations#7]
Even tough I am the Pod owner I am getting 403 errors when trying to access `.meta.acl` in the Pod root. The file `.meta` exists, but Sharing cannot be edited due to this.

**Comment by jaxoncreed** [comment]
Ah yep. Looks like there were still problems with the link updates for ACLs. Fixing now

**Comment by jaxoncreed** [comment]
The .acl is now properly updated. Let me know if there are any additional problems.

**Comment by angelo-v** [comment]
@jaxoncreed It works for the meta.acl now, thanks, but I am still having problems fetching e.g. `https://welcome.solidcommunity.net/config.js.acl`
